server:
  port: 5000

spring:
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true


klaytn:
  api:
    access-key:
    secret-key:
    authorization:
    chain-id:

ipfs:
  host:
  port:
